package agent

import "time"

func DefaultAgents(now time.Time) []AgentSpec {
	return []AgentSpec{
		{
			ID:           "tracking-agent",
			Name:         "Tracking Agent",
			Kind:         "python-worker",
			Version:      "v0.1",
			Description:  "Runs detection and multi-object tracking jobs.",
			Capabilities: []string{"detect", "track", "convert-tracks"},
			ToolIDs:      []string{"yolo26x-botsort"},
			Runtime:      "python",
			PolicyTags:   []string{"data-read", "artifact-write"},
			Status:       AgentStatusAvailable,
			CreatedAt:    now,
			UpdatedAt:    now,
		},
		{
			ID:           "segmentation-agent",
			Name:         "Segmentation Agent",
			Kind:         "python-worker",
			Version:      "v0.1",
			Description:  "Generates and propagates masks for selected objects.",
			Capabilities: []string{"segment", "mask-propagation"},
			ToolIDs:      []string{"sam2-propagation"},
			Runtime:      "python",
			PolicyTags:   []string{"gpu", "artifact-write"},
			Status:       AgentStatusAvailable,
			CreatedAt:    now,
			UpdatedAt:    now,
		},
		{
			ID:           "vlm-label-agent",
			Name:         "VLM Label Agent",
			Kind:         "python-worker",
			Version:      "v0.1",
			Description:  "Uses multimodal grounding models to propose object labels and anomaly hints.",
			Capabilities: []string{"ground", "label", "describe"},
			ToolIDs:      []string{"locateanything-grounding"},
			Runtime:      "python",
			PolicyTags:   []string{"gpu", "model-read"},
			Status:       AgentStatusAvailable,
			CreatedAt:    now,
			UpdatedAt:    now,
		},
		{
			ID:           "training-agent",
			Name:         "Training Agent",
			Kind:         "python-worker",
			Version:      "v0.1",
			Description:  "Starts model training jobs from curated datasets and records produced checkpoints.",
			Capabilities: []string{"train", "checkpoint", "metrics"},
			ToolIDs:      []string{"training-runner"},
			Runtime:      "python",
			PolicyTags:   []string{"gpu", "artifact-write", "model-write"},
			Status:       AgentStatusAvailable,
			CreatedAt:    now,
			UpdatedAt:    now,
		},
		{
			ID:           "evaluation-agent",
			Name:         "Evaluation Agent",
			Kind:         "python-worker",
			Version:      "v0.1",
			Description:  "Evaluates models and writes comparable metrics reports.",
			Capabilities: []string{"evaluate", "compare", "report-metrics"},
			ToolIDs:      []string{"evaluation-runner"},
			Runtime:      "python",
			PolicyTags:   []string{"data-read", "model-read", "artifact-write"},
			Status:       AgentStatusAvailable,
			CreatedAt:    now,
			UpdatedAt:    now,
		},
		{
			ID:           "report-agent",
			Name:         "Report Agent",
			Kind:         "go-service",
			Version:      "v0.1",
			Description:  "Assembles workflow state, metrics, and audit events into operator-facing reports.",
			Capabilities: []string{"report", "dashboard-export"},
			ToolIDs:      []string{"report-exporter"},
			Runtime:      "go",
			PolicyTags:   []string{"metadata-read"},
			Status:       AgentStatusAvailable,
			CreatedAt:    now,
			UpdatedAt:    now,
		},
	}
}

func DefaultTools(now time.Time) []ToolSpec {
	return []ToolSpec{
		{
			ID:              "yolo26x-botsort",
			Name:            "YOLO26X + BoT-SORT",
			Kind:            "python-tool",
			Version:         "v0.1",
			Description:     "Detection and tracking adapter for existing ShanghaiTech derived tracks.",
			PermissionLevel: "workspace",
			Runtime:         "python",
			Status:          ToolStatusAvailable,
			CreatedAt:       now,
			UpdatedAt:       now,
		},
		{
			ID:              "sam2-propagation",
			Name:            "SAM2 Propagation",
			Kind:            "python-tool",
			Version:         "v0.1",
			Description:     "Interactive segmentation and mask propagation adapter.",
			PermissionLevel: "workspace-gpu",
			Runtime:         "python",
			Status:          ToolStatusAvailable,
			CreatedAt:       now,
			UpdatedAt:       now,
		},
		{
			ID:              "locateanything-grounding",
			Name:            "LocateAnything Grounding",
			Kind:            "python-tool",
			Version:         "v0.1",
			Description:     "Grounding model adapter for multimodal object localization.",
			PermissionLevel: "workspace-gpu",
			Runtime:         "python",
			Status:          ToolStatusAvailable,
			CreatedAt:       now,
			UpdatedAt:       now,
		},
		{
			ID:              "training-runner",
			Name:            "Training Runner",
			Kind:            "python-tool",
			Version:         "v0.1",
			Description:     "Executes training recipes and emits model checkpoints plus metrics.",
			PermissionLevel: "workspace-gpu",
			Runtime:         "python",
			Status:          ToolStatusAvailable,
			CreatedAt:       now,
			UpdatedAt:       now,
		},
		{
			ID:              "evaluation-runner",
			Name:            "Evaluation Runner",
			Kind:            "python-tool",
			Version:         "v0.1",
			Description:     "Runs model evaluation jobs against registered datasets.",
			PermissionLevel: "workspace",
			Runtime:         "python",
			Status:          ToolStatusAvailable,
			CreatedAt:       now,
			UpdatedAt:       now,
		},
		{
			ID:              "report-exporter",
			Name:            "Report Exporter",
			Kind:            "go-tool",
			Version:         "v0.1",
			Description:     "Exports workflow summaries and audit reports.",
			PermissionLevel: "metadata",
			Runtime:         "go",
			Status:          ToolStatusAvailable,
			CreatedAt:       now,
			UpdatedAt:       now,
		},
	}
}

func DefaultWorkflows(now time.Time) []WorkflowSpec {
	return []WorkflowSpec{
		{
			ID:          "human-loop-autolabel",
			Name:        "Human Loop Auto Label",
			Version:     "v0.1",
			Description: "Tracking, model-assisted labeling, human review, training, and evaluation loop.",
			Trigger:     "manual",
			AgentIDs:    []string{"tracking-agent", "vlm-label-agent", "training-agent", "evaluation-agent", "report-agent"},
			ToolIDs:     []string{"yolo26x-botsort", "locateanything-grounding", "training-runner", "evaluation-runner", "report-exporter"},
			Status:      WorkflowStatusAvailable,
			CreatedAt:   now,
			UpdatedAt:   now,
			Steps: []WorkflowStep{
				{ID: "track", Name: "Track Objects", AgentID: "tracking-agent", ToolID: "yolo26x-botsort", Action: "track", PolicyTags: []string{"data-read", "artifact-write"}},
				{ID: "label", Name: "Propose Labels", AgentID: "vlm-label-agent", ToolID: "locateanything-grounding", Action: "label", DependsOn: []string{"track"}, PolicyTags: []string{"model-read"}},
				{ID: "review", Name: "Human Review", Action: "human_review", DependsOn: []string{"label"}, PolicyTags: []string{"human-required"}},
				{ID: "train", Name: "Train Model", AgentID: "training-agent", ToolID: "training-runner", Action: "train", DependsOn: []string{"review"}, PolicyTags: []string{"gpu", "model-write"}},
				{ID: "evaluate", Name: "Evaluate Model", AgentID: "evaluation-agent", ToolID: "evaluation-runner", Action: "evaluate", DependsOn: []string{"train"}, PolicyTags: []string{"model-read"}},
				{ID: "report", Name: "Publish Report", AgentID: "report-agent", ToolID: "report-exporter", Action: "report", DependsOn: []string{"evaluate"}, PolicyTags: []string{"metadata-read"}},
			},
		},
		{
			ID:          "dataset-to-tracking",
			Name:        "Dataset To Tracking",
			Version:     "v0.1",
			Description: "Runs only the detection/tracking stage and stores derived labels for review.",
			Trigger:     "manual",
			AgentIDs:    []string{"tracking-agent"},
			ToolIDs:     []string{"yolo26x-botsort"},
			Status:      WorkflowStatusAvailable,
			CreatedAt:   now,
			UpdatedAt:   now,
			Steps: []WorkflowStep{
				{ID: "track", Name: "Track Objects", AgentID: "tracking-agent", ToolID: "yolo26x-botsort", Action: "track", PolicyTags: []string{"data-read", "artifact-write"}},
			},
		},
	}
}
