package agent

import "time"

func DefaultAgents(now time.Time) []AgentSpec {
	return []AgentSpec{
		{
			ID:           "data-collection-agent",
			Name:         "Data Collection Agent",
			Kind:         "go-service",
			Version:      "v0.1",
			Description:  "Plans dataset intake from folders, uploads, manifests, object stores, streams, or external connectors.",
			Capabilities: []string{"collect-data", "register-source", "profile-source"},
			ToolIDs:      []string{"data-source-connector", "dataset-profiler"},
			Runtime:      "go",
			PolicyTags:   []string{"data-read", "source-register", "tenant-scope"},
			Status:       AgentStatusAvailable,
			CreatedAt:    now,
			UpdatedAt:    now,
		},
		{
			ID:           "tracking-agent",
			Name:         "Perception Agent",
			Kind:         "python-worker",
			Version:      "v0.1",
			Description:  "Runs pluggable perception jobs and converts outputs into reviewable artifacts.",
			Capabilities: []string{"perceive", "track", "convert-artifacts"},
			ToolIDs:      []string{"perception-adapter"},
			Runtime:      "python",
			PolicyTags:   []string{"data-read", "artifact-write"},
			Status:       AgentStatusAvailable,
			CreatedAt:    now,
			UpdatedAt:    now,
		},
		{
			ID:           "segmentation-agent",
			Name:         "Segmentation Agent",
			Kind:         "python-worker",
			Version:      "v0.1",
			Description:  "Generates and propagates spatial masks through a pluggable model service.",
			Capabilities: []string{"segment", "mask-propagation"},
			ToolIDs:      []string{"segmentation-adapter"},
			Runtime:      "python",
			PolicyTags:   []string{"gpu", "artifact-write"},
			Status:       AgentStatusAvailable,
			CreatedAt:    now,
			UpdatedAt:    now,
		},
		{
			ID:           "vlm-label-agent",
			Name:         "Multimodal Label Agent",
			Kind:         "python-worker",
			Version:      "v0.1",
			Description:  "Uses model adapters to propose object labels, descriptions, and anomaly hints.",
			Capabilities: []string{"ground", "label", "describe"},
			ToolIDs:      []string{"multimodal-label-adapter"},
			Runtime:      "python",
			PolicyTags:   []string{"gpu", "model-read"},
			Status:       AgentStatusAvailable,
			CreatedAt:    now,
			UpdatedAt:    now,
		},
		{
			ID:           "training-agent",
			Name:         "Training Agent",
			Kind:         "python-worker",
			Version:      "v0.1",
			Description:  "Starts model training jobs from curated datasets and records produced checkpoints.",
			Capabilities: []string{"train", "checkpoint", "metrics"},
			ToolIDs:      []string{"training-runner"},
			Runtime:      "python",
			PolicyTags:   []string{"gpu", "artifact-write", "model-write"},
			Status:       AgentStatusAvailable,
			CreatedAt:    now,
			UpdatedAt:    now,
		},
		{
			ID:           "governance-agent",
			Name:         "Governance Agent",
			Kind:         "go-service",
			Version:      "v0.1",
			Description:  "Checks policy, schema, lineage, tenant boundaries, budget, and release readiness across the lifecycle.",
			Capabilities: []string{"enforce-policy", "validate-schema", "check-lineage", "gate-release"},
			ToolIDs:      []string{"governance-checker", "release-gate"},
			Runtime:      "go",
			PolicyTags:   []string{"policy-read", "audit-write", "approval-required"},
			Status:       AgentStatusAvailable,
			CreatedAt:    now,
			UpdatedAt:    now,
		},
		{
			ID:           "evaluation-agent",
			Name:         "Evaluation Agent",
			Kind:         "python-worker",
			Version:      "v0.1",
			Description:  "Evaluates models and writes comparable metrics reports.",
			Capabilities: []string{"evaluate", "compare", "report-metrics"},
			ToolIDs:      []string{"evaluation-runner"},
			Runtime:      "python",
			PolicyTags:   []string{"data-read", "model-read", "artifact-write"},
			Status:       AgentStatusAvailable,
			CreatedAt:    now,
			UpdatedAt:    now,
		},
		{
			ID:           "report-agent",
			Name:         "Report Agent",
			Kind:         "go-service",
			Version:      "v0.1",
			Description:  "Assembles workflow state, metrics, and audit events into operator-facing reports.",
			Capabilities: []string{"report", "dashboard-export"},
			ToolIDs:      []string{"report-exporter"},
			Runtime:      "go",
			PolicyTags:   []string{"metadata-read"},
			Status:       AgentStatusAvailable,
			CreatedAt:    now,
			UpdatedAt:    now,
		},
		{
			ID:           "release-agent",
			Name:         "Release Agent",
			Kind:         "go-service",
			Version:      "v0.1",
			Description:  "Coordinates promotion gates, staged rollout metadata, and rollback decisions.",
			Capabilities: []string{"promote", "canary", "rollback"},
			ToolIDs:      []string{"release-gate"},
			Runtime:      "go",
			PolicyTags:   []string{"approval-required", "model-write"},
			Status:       AgentStatusAvailable,
			CreatedAt:    now,
			UpdatedAt:    now,
		},
		{
			ID:           "deployment-agent",
			Name:         "Deployment Agent",
			Kind:         "go-service",
			Version:      "v0.1",
			Description:  "Deploys approved model versions through environment promotion, rollout, and rollback controls.",
			Capabilities: []string{"deploy", "route-traffic", "rollback"},
			ToolIDs:      []string{"deployment-controller"},
			Runtime:      "go",
			PolicyTags:   []string{"deployment-write", "approval-required", "rollback-ready"},
			Status:       AgentStatusAvailable,
			CreatedAt:    now,
			UpdatedAt:    now,
		},
		{
			ID:           "monitoring-agent",
			Name:         "Monitoring Agent",
			Kind:         "go-service",
			Version:      "v0.1",
			Description:  "Collects online quality, drift, cost, latency, and policy signals after deployment.",
			Capabilities: []string{"monitor", "detect-drift", "trigger-feedback"},
			ToolIDs:      []string{"monitoring-collector"},
			Runtime:      "go",
			PolicyTags:   []string{"metrics-read", "audit-write", "feedback"},
			Status:       AgentStatusAvailable,
			CreatedAt:    now,
			UpdatedAt:    now,
		},
	}
}

func DefaultTools(now time.Time) []ToolSpec {
	return []ToolSpec{
		{
			ID:               "data-source-connector",
			Name:             "Data Source Connector",
			Kind:             "go-tool",
			Version:          "v0.1",
			Description:      "Registers raw data sources and creates source manifests without copying large artifacts into Git.",
			PermissionLevel:  "workspace",
			PermissionScopes: []string{"source:read", "dataset:register", "metadata:write"},
			RiskLevel:        "medium",
			SandboxPolicyID:  "metadata-only",
			BudgetPolicyID:   "standard-control-plane",
			Runtime:          "go",
			Status:           ToolStatusAvailable,
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "dataset-profiler",
			Name:             "Dataset Profiler",
			Kind:             "go-tool",
			Version:          "v0.1",
			Description:      "Profiles schema, volume, formats, missing values, class distribution, and privacy risk before curation.",
			PermissionLevel:  "workspace",
			PermissionScopes: []string{"dataset:read", "metadata:write", "audit:write"},
			RiskLevel:        "medium",
			SandboxPolicyID:  "metadata-only",
			BudgetPolicyID:   "standard-control-plane",
			Runtime:          "go",
			Status:           ToolStatusAvailable,
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "perception-adapter",
			Name:             "Perception Adapter",
			Kind:             "python-tool",
			Version:          "v0.1",
			Description:      "Pluggable video perception adapter for detection, tracking, and conversion outputs.",
			PermissionLevel:  "workspace",
			PermissionScopes: []string{"data:read", "artifact:write"},
			RiskLevel:        "medium",
			SandboxPolicyID:  "python-worker-gpu-readwrite",
			BudgetPolicyID:   "bounded-batch",
			Runtime:          "python",
			Status:           ToolStatusAvailable,
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "segmentation-adapter",
			Name:             "Segmentation Adapter",
			Kind:             "python-tool",
			Version:          "v0.1",
			Description:      "Pluggable segmentation and mask propagation adapter.",
			PermissionLevel:  "workspace-gpu",
			PermissionScopes: []string{"data:read", "artifact:write", "gpu:use"},
			RiskLevel:        "medium",
			SandboxPolicyID:  "python-worker-gpu-readwrite",
			BudgetPolicyID:   "bounded-batch",
			Runtime:          "python",
			Status:           ToolStatusAvailable,
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "multimodal-label-adapter",
			Name:             "Multimodal Label Adapter",
			Kind:             "python-tool",
			Version:          "v0.1",
			Description:      "Pluggable multimodal labeling and grounding adapter.",
			PermissionLevel:  "workspace-gpu",
			PermissionScopes: []string{"data:read", "model:read", "artifact:write"},
			RiskLevel:        "high",
			ApprovalRequired: true,
			SandboxPolicyID:  "model-adapter-restricted",
			BudgetPolicyID:   "model-call-budget",
			Runtime:          "python",
			Status:           ToolStatusAvailable,
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "data-curation-pipeline",
			Name:             "Data Curation Pipeline",
			Kind:             "go-tool",
			Version:          "v0.1",
			Description:      "Applies authorization, redaction, quality checks, and lineage before training ingest.",
			PermissionLevel:  "metadata",
			PermissionScopes: []string{"dataset:read", "dataset:version", "lineage:write"},
			RiskLevel:        "high",
			ApprovalRequired: true,
			SandboxPolicyID:  "metadata-only",
			BudgetPolicyID:   "standard-control-plane",
			Runtime:          "go",
			Status:           ToolStatusAvailable,
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "governance-checker",
			Name:             "Governance Checker",
			Kind:             "go-tool",
			Version:          "v0.1",
			Description:      "Evaluates policy, schema, lineage, tenant isolation, budget, and approval requirements for lifecycle steps.",
			PermissionLevel:  "metadata",
			PermissionScopes: []string{"policy:read", "schema:read", "lineage:read", "audit:write"},
			RiskLevel:        "high",
			ApprovalRequired: true,
			SandboxPolicyID:  "metadata-only",
			BudgetPolicyID:   "standard-control-plane",
			Runtime:          "go",
			Status:           ToolStatusAvailable,
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "training-runner",
			Name:             "Training Runner",
			Kind:             "python-tool",
			Version:          "v0.1",
			Description:      "Executes training recipes and emits model checkpoints plus metrics.",
			PermissionLevel:  "workspace-gpu",
			PermissionScopes: []string{"dataset:read", "model:write", "gpu:use"},
			RiskLevel:        "high",
			ApprovalRequired: true,
			SandboxPolicyID:  "training-worker-isolated",
			BudgetPolicyID:   "training-budget",
			Runtime:          "python",
			Status:           ToolStatusAvailable,
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "evaluation-runner",
			Name:             "Evaluation Runner",
			Kind:             "python-tool",
			Version:          "v0.1",
			Description:      "Runs model evaluation jobs against registered datasets.",
			PermissionLevel:  "workspace",
			PermissionScopes: []string{"dataset:read", "model:read", "report:write"},
			RiskLevel:        "medium",
			SandboxPolicyID:  "evaluation-worker-readonly",
			BudgetPolicyID:   "evaluation-budget",
			Runtime:          "python",
			Status:           ToolStatusAvailable,
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "report-exporter",
			Name:             "Report Exporter",
			Kind:             "go-tool",
			Version:          "v0.1",
			Description:      "Exports workflow summaries and audit reports.",
			PermissionLevel:  "metadata",
			PermissionScopes: []string{"metadata:read", "report:write"},
			RiskLevel:        "low",
			SandboxPolicyID:  "metadata-only",
			BudgetPolicyID:   "standard-control-plane",
			Runtime:          "go",
			Status:           ToolStatusAvailable,
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "release-gate",
			Name:             "Release Gate",
			Kind:             "go-tool",
			Version:          "v0.1",
			Description:      "Checks evaluation, policy, approval, rollout, and rollback requirements before promotion.",
			PermissionLevel:  "metadata",
			PermissionScopes: []string{"model:read", "model:promote", "policy:read", "audit:write"},
			RiskLevel:        "high",
			ApprovalRequired: true,
			SandboxPolicyID:  "metadata-only",
			BudgetPolicyID:   "standard-control-plane",
			Runtime:          "go",
			Status:           ToolStatusAvailable,
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "deployment-controller",
			Name:             "Deployment Controller",
			Kind:             "go-tool",
			Version:          "v0.1",
			Description:      "Deploys approved artifacts to a target environment with traffic policy and rollback metadata.",
			PermissionLevel:  "deployment",
			PermissionScopes: []string{"model:read", "deployment:write", "traffic:update", "audit:write"},
			RiskLevel:        "high",
			ApprovalRequired: true,
			SandboxPolicyID:  "metadata-only",
			BudgetPolicyID:   "deployment-budget",
			Runtime:          "go",
			Status:           ToolStatusAvailable,
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "monitoring-collector",
			Name:             "Monitoring Collector",
			Kind:             "go-tool",
			Version:          "v0.1",
			Description:      "Collects post-deployment quality, drift, latency, cost, and policy signals for feedback loops.",
			PermissionLevel:  "metadata",
			PermissionScopes: []string{"metrics:read", "trace:read", "feedback:write", "audit:write"},
			RiskLevel:        "medium",
			SandboxPolicyID:  "metadata-only",
			BudgetPolicyID:   "standard-control-plane",
			Runtime:          "go",
			Status:           ToolStatusAvailable,
			CreatedAt:        now,
			UpdatedAt:        now,
		},
	}
}

func DefaultWorkflows(now time.Time) []WorkflowSpec {
	return []WorkflowSpec{
		{
			ID:          "data-to-deployment-lifecycle",
			Name:        "Data To Deployment Lifecycle",
			Version:     "v0.1",
			Description: "Primary CLI-driven agent workflow from data collection through governance, curation, training, evaluation, release, deployment, monitoring, and feedback.",
			Trigger:     "cli",
			AgentIDs: []string{
				"data-collection-agent",
				"governance-agent",
				"vlm-label-agent",
				"training-agent",
				"evaluation-agent",
				"release-agent",
				"deployment-agent",
				"monitoring-agent",
				"report-agent",
			},
			ToolIDs: []string{
				"data-source-connector",
				"dataset-profiler",
				"data-curation-pipeline",
				"governance-checker",
				"multimodal-label-adapter",
				"training-runner",
				"evaluation-runner",
				"release-gate",
				"deployment-controller",
				"monitoring-collector",
				"report-exporter",
			},
			Metadata: map[string]string{
				"entrypoint": "cli-agent",
				"domain":     "full-lifecycle-agent",
				"boundary":   "explicit contracts from raw source to deployed model",
			},
			Status:    WorkflowStatusAvailable,
			CreatedAt: now,
			UpdatedAt: now,
			Steps: []WorkflowStep{
				{ID: "collect", Name: "Collect Or Register Data", AgentID: "data-collection-agent", ToolID: "data-source-connector", Action: "collect", PolicyTags: []string{"tenant-scope", "source-register", "audit-write"}, FailurePolicyID: "retry-idempotent-then-hold", TimeoutSeconds: 600},
				{ID: "profile", Name: "Profile Dataset", AgentID: "data-collection-agent", ToolID: "dataset-profiler", Action: "profile", DependsOn: []string{"collect"}, PolicyTags: []string{"schema-validate", "privacy-risk", "budget-check"}, FailurePolicyID: "retry-idempotent-then-hold", TimeoutSeconds: 900},
				{ID: "govern_data", Name: "Govern Training Eligibility", AgentID: "governance-agent", ToolID: "governance-checker", Action: "govern_data", DependsOn: []string{"profile"}, PolicyTags: []string{"consent", "tenant-isolation", "lineage-check"}, ApprovalGateID: "training-data-ingest", FailurePolicyID: "stop-no-compensation", TimeoutSeconds: 300},
				{ID: "curate", Name: "Curate Dataset Version", ToolID: "data-curation-pipeline", Action: "curate", DependsOn: []string{"govern_data"}, PolicyTags: []string{"redaction", "quality", "dedupe", "split-isolation", "lineage-write"}, FailurePolicyID: "stop-no-compensation", TimeoutSeconds: 1200},
				{ID: "label_or_review", Name: "Label Or Human Review", AgentID: "vlm-label-agent", ToolID: "multimodal-label-adapter", Action: "label_or_review", DependsOn: []string{"curate"}, PolicyTags: []string{"model-context-scan", "human-required", "label-quality"}, ApprovalGateID: "label-quality", FailurePolicyID: "hold-for-approval", TimeoutSeconds: 3600},
				{ID: "train", Name: "Train Candidate Model", AgentID: "training-agent", ToolID: "training-runner", Action: "train", DependsOn: []string{"label_or_review"}, PolicyTags: []string{"gpu", "model-write", "budget-check"}, ApprovalGateID: "training-run", FailurePolicyID: "resume-or-rollback", TimeoutSeconds: 86400},
				{ID: "evaluate", Name: "Evaluate Candidate", AgentID: "evaluation-agent", ToolID: "evaluation-runner", Action: "evaluate", DependsOn: []string{"train"}, PolicyTags: []string{"eval-suite", "safety-eval", "cost-latency"}, FailurePolicyID: "retry-idempotent-then-hold", TimeoutSeconds: 7200},
				{ID: "release", Name: "Release Promotion Gate", AgentID: "release-agent", ToolID: "release-gate", Action: "release", DependsOn: []string{"evaluate"}, PolicyTags: []string{"approval-required", "canary", "rollback-ready"}, ApprovalGateID: "model-promotion", FailurePolicyID: "stop-no-compensation", TimeoutSeconds: 600},
				{ID: "deploy", Name: "Deploy Approved Version", AgentID: "deployment-agent", ToolID: "deployment-controller", Action: "deploy", DependsOn: []string{"release"}, PolicyTags: []string{"deployment-write", "traffic-policy", "audit-write"}, ApprovalGateID: "production-deployment", FailurePolicyID: "hold-for-approval", TimeoutSeconds: 1800},
				{ID: "monitor", Name: "Monitor And Trigger Feedback", AgentID: "monitoring-agent", ToolID: "monitoring-collector", Action: "monitor", DependsOn: []string{"deploy"}, PolicyTags: []string{"quality-monitor", "drift-monitor", "cost-monitor", "feedback"}, FailurePolicyID: "retry-idempotent-then-hold", TimeoutSeconds: 3600},
				{ID: "report", Name: "Publish Lifecycle Report", AgentID: "report-agent", ToolID: "report-exporter", Action: "report", DependsOn: []string{"monitor"}, PolicyTags: []string{"metadata-read", "audit-write", "lineage-read"}, TimeoutSeconds: 300},
			},
		},
		{
			ID:          "human-loop-autolabel",
			Name:        "Human Loop Auto Label",
			Version:     "v0.1",
			Description: "Tracking, model-assisted labeling, human review, training, and evaluation loop.",
			Trigger:     "manual",
			AgentIDs:    []string{"tracking-agent", "vlm-label-agent", "training-agent", "evaluation-agent", "release-agent", "report-agent"},
			ToolIDs:     []string{"perception-adapter", "multimodal-label-adapter", "data-curation-pipeline", "training-runner", "evaluation-runner", "release-gate", "report-exporter"},
			Metadata: map[string]string{
				"domain":   "training-platform",
				"boundary": "versioned datasets and model artifacts",
			},
			Status:    WorkflowStatusAvailable,
			CreatedAt: now,
			UpdatedAt: now,
			Steps: []WorkflowStep{
				{ID: "perceive", Name: "Create Review Candidates", AgentID: "tracking-agent", ToolID: "perception-adapter", Action: "perceive", PolicyTags: []string{"data-read", "artifact-write", "tool-preflight"}, FailurePolicyID: "retry-idempotent-then-hold", TimeoutSeconds: 3600},
				{ID: "label", Name: "Propose Labels", AgentID: "vlm-label-agent", ToolID: "multimodal-label-adapter", Action: "label", DependsOn: []string{"perceive"}, PolicyTags: []string{"model-read", "model-context-scan"}, ApprovalGateID: "high-risk-model-use", FailurePolicyID: "hold-for-review", TimeoutSeconds: 1800},
				{ID: "curate", Name: "Curate Training Data", ToolID: "data-curation-pipeline", Action: "curate", DependsOn: []string{"label"}, PolicyTags: []string{"data-authorization", "redaction", "lineage-write"}, ApprovalGateID: "training-data-ingest", FailurePolicyID: "stop-no-compensation", TimeoutSeconds: 600},
				{ID: "review", Name: "Human Review", Action: "human_review", DependsOn: []string{"curate"}, PolicyTags: []string{"human-required"}, ApprovalGateID: "label-quality"},
				{ID: "train", Name: "Train Candidate", AgentID: "training-agent", ToolID: "training-runner", Action: "train", DependsOn: []string{"review"}, PolicyTags: []string{"gpu", "model-write", "budget-check"}, ApprovalGateID: "training-run", FailurePolicyID: "resume-or-rollback", TimeoutSeconds: 86400},
				{ID: "evaluate", Name: "Evaluate Candidate", AgentID: "evaluation-agent", ToolID: "evaluation-runner", Action: "evaluate", DependsOn: []string{"train"}, PolicyTags: []string{"model-read", "eval-suite"}, FailurePolicyID: "retry-idempotent-then-hold", TimeoutSeconds: 7200},
				{ID: "release", Name: "Promotion Gate", AgentID: "release-agent", ToolID: "release-gate", Action: "promote", DependsOn: []string{"evaluate"}, PolicyTags: []string{"approval-required", "canary", "rollback-ready"}, ApprovalGateID: "model-promotion", FailurePolicyID: "stop-no-compensation", TimeoutSeconds: 600},
				{ID: "report", Name: "Publish Report", AgentID: "report-agent", ToolID: "report-exporter", Action: "report", DependsOn: []string{"release"}, PolicyTags: []string{"metadata-read", "audit-write"}, TimeoutSeconds: 300},
			},
		},
		{
			ID:          "dataset-to-tracking",
			Name:        "Dataset To Perception Artifacts",
			Version:     "v0.1",
			Description: "Runs only the perception stage and stores derived labels for review.",
			Trigger:     "manual",
			AgentIDs:    []string{"tracking-agent"},
			ToolIDs:     []string{"perception-adapter"},
			Metadata: map[string]string{
				"domain":   "training-platform",
				"boundary": "derived review artifacts",
			},
			Status:    WorkflowStatusAvailable,
			CreatedAt: now,
			UpdatedAt: now,
			Steps: []WorkflowStep{
				{ID: "perceive", Name: "Create Review Candidates", AgentID: "tracking-agent", ToolID: "perception-adapter", Action: "perceive", PolicyTags: []string{"data-read", "artifact-write", "tool-preflight"}, FailurePolicyID: "retry-idempotent-then-hold", TimeoutSeconds: 3600},
			},
		},
		{
			ID:          "agent-serving-request",
			Name:        "Agent Serving Request",
			Version:     "v0.1",
			Description: "Runtime path for user request routing, tool preflight, execution, result filtering, and audit.",
			Trigger:     "api",
			AgentIDs:    []string{"report-agent"},
			ToolIDs:     []string{"report-exporter"},
			Metadata: map[string]string{
				"domain":   "agent-serving",
				"boundary": "session-scoped runtime state",
			},
			Status:    WorkflowStatusAvailable,
			CreatedAt: now,
			UpdatedAt: now,
			Steps: []WorkflowStep{
				{ID: "request_guard", Name: "Request Guard", Action: "guard_request", PolicyTags: []string{"auth", "tenant-scope", "context-scan"}, FailurePolicyID: "reject-with-audit", TimeoutSeconds: 30},
				{ID: "plan", Name: "Plan Action", Action: "plan", DependsOn: []string{"request_guard"}, PolicyTags: []string{"schema-validate", "budget-check"}, FailurePolicyID: "ask-user-or-hold", TimeoutSeconds: 120},
				{ID: "tool_preflight", Name: "Tool Preflight", Action: "preflight_tool", DependsOn: []string{"plan"}, PolicyTags: []string{"tool-scope", "approval-check", "secret-scope"}, ApprovalGateID: "dangerous-tool", FailurePolicyID: "hold-for-approval", TimeoutSeconds: 60},
				{ID: "execute", Name: "Execute", Action: "execute_tool", DependsOn: []string{"tool_preflight"}, PolicyTags: []string{"sandbox", "resource-limit", "trace"}, FailurePolicyID: "retry-idempotent-then-hold", TimeoutSeconds: 3600},
				{ID: "egress", Name: "Result Filter", Action: "filter_result", DependsOn: []string{"execute"}, PolicyTags: []string{"output-filter", "privacy-check", "audit-write"}, FailurePolicyID: "hold-for-review", TimeoutSeconds: 60},
			},
		},
	}
}
