$env:ANTHROPIC_BASE_URL = "https://token-plan-cn.xiaomimimo.com/anthropic"
$env:ANTHROPIC_AUTH_TOKEN = "replace_me"
$env:ANTHROPIC_MODEL = "mimo-v2.5-pro"
$env:ANTHROPIC_DEFAULT_SONNET_MODEL = "mimo-v2.5-pro"
$env:ANTHROPIC_DEFAULT_OPUS_MODEL = "mimo-v2.5-pro"
$env:ANTHROPIC_DEFAULT_HAIKU_MODEL = "mimo-v2.5-pro"
$env:MIMO_OPENAI_BASE_URL = "https://token-plan-cn.xiaomimimo.com/v1"
$env:MIMO_DEFAULT_MODEL = "mimo-v2.5-pro"
$env:MIMO_VISION_MODEL = "mimo-v2.5"
Write-Host "Mimo provider environment variables are set for this PowerShell session."

